
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasksdb
    username: task
    password: task
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: true